//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Demo001 {
            get {
                return ResourceManager.GetString("Demo001", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Form1_Name {
            get {
                return ResourceManager.GetString("Form1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Today,The main work content 的本地化字符串。
        /// </summary>
        internal static string Form2_DataWorkContent {
            get {
                return ResourceManager.GetString("Form2_DataWorkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 No. 的本地化字符串。
        /// </summary>
        internal static string Form2_No {
            get {
                return ResourceManager.GetString("Form2_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 ProjectName 的本地化字符串。
        /// </summary>
        internal static string Form2_ProjectName {
            get {
                return ResourceManager.GetString("Form2_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Please select the project name! 的本地化字符串。
        /// </summary>
        internal static string Form2_SelectTheProject {
            get {
                return ResourceManager.GetString("Form2_SelectTheProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 XDropDownList 的本地化字符串。
        /// </summary>
        internal static string Form2_String001 {
            get {
                return ResourceManager.GetString("Form2_String001", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 XCheckBoxList 的本地化字符串。
        /// </summary>
        internal static string Form2_String002 {
            get {
                return ResourceManager.GetString("Form2_String002", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 XRadioButton 的本地化字符串。
        /// </summary>
        internal static string Form2_String003 {
            get {
                return ResourceManager.GetString("Form2_String003", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Please select the Type! 的本地化字符串。
        /// </summary>
        internal static string Form2_String004 {
            get {
                return ResourceManager.GetString("Form2_String004", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Green Tea 的本地化字符串。
        /// </summary>
        internal static string Form2_String005 {
            get {
                return ResourceManager.GetString("Form2_String005", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Tieguanyin Tea 的本地化字符串。
        /// </summary>
        internal static string Form2_String006 {
            get {
                return ResourceManager.GetString("Form2_String006", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Jasmine Tea 的本地化字符串。
        /// </summary>
        internal static string Form2_String007 {
            get {
                return ResourceManager.GetString("Form2_String007", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Chrysanthemum Tea  的本地化字符串。
        /// </summary>
        internal static string Form2_String008 {
            get {
                return ResourceManager.GetString("Form2_String008", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Longjing Tea 的本地化字符串。
        /// </summary>
        internal static string Form2_String009 {
            get {
                return ResourceManager.GetString("Form2_String009", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 WorkContent 的本地化字符串。
        /// </summary>
        internal static string Form2_WorkContent {
            get {
                return ResourceManager.GetString("Form2_WorkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 WorkData 的本地化字符串。
        /// </summary>
        internal static string Form2_WorkData {
            get {
                return ResourceManager.GetString("Form2_WorkData", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 WorkTime 的本地化字符串。
        /// </summary>
        internal static string Form2_WorkTime {
            get {
                return ResourceManager.GetString("Form2_WorkTime", resourceCulture);
            }
        }
    }
}
